name: Bug report
description: Report a bug
title: "bug: "
labels: [bug]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: What did you expect to happen?
      placeholder: Steps, logs, screenshots.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: How to reproduce
      description: Minimal repro steps.
      placeholder: "1. ... 2. ..."
    validations:
      required: true
  - type: input
    id: module
    attributes:
      label: Module / repo
      placeholder: e.g. comptox-mcp
  - type: textarea
    id: env
    attributes:
      label: Environment
      placeholder: OS, Python version, Docker, etc.
