name: Feature request
description: Suggest an idea
title: "feature: "
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is it useful?
